version: '3'
services:
  todo-frontend:
    build: .
    ports:
      - "7777:7777"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_PRODUCTION_ENDPOINT=${NEXT_PUBLIC_PRODUCTION_ENDPOINT}